### ISSUE TITLE
Tableau 2019.4.1 - Submit Button Does Not Work

### ISSUE THREAD

**Issue by jasonlones** [lsgs/redcap-tableau-wdc#15]
Recent up-versioning to 2019.4.1 has rendered the 'Submit' button ineffective.

**Comment by aarenson** [comment]
Seeing the same problem with 2019.4.3

**Comment by lsgs** [comment]
Yes I get this too now I got to updating my Tableau to 2019.4. It's related to the change they've made to the internal browser but I'm struggling to tackle the problem because their debugging mechanism (described here https://tableau.github.io/webdataconnector/docs/wdc_debugging.html#debug-chrome) is resisting all attempts to get working.
![image](https://user-images.githubusercontent.com/7444426/74709245-cef2f600-5272-11ea-82a0-ccd333cab154.png)

Are you able to try?

**Comment by aarenson** [comment]
Using the debugging method you linked above, from within the TWDC within Tableau 2019.4, after entering my API token, when I click 'Submit', the Chrome Console shows:

```
TypeError: tableau.submit is not a function
    at HTMLButtonElement.<anonymous> (?type=module&prefix=tableau_connector&page=wdc&NOAUTH:442)
    at HTMLButtonElement.dispatch (base.js:6)
    at HTMLButtonElement.v.handle (base.js:6)
```

**Comment by aarenson** [comment]
I think the problem is that the default version of the tableauwdc javascript library being used isn't compatible with 2019.4. I went to Control Center->External Modules, opened the configuration parameters for REDCap TWDC and changed Tableau connector JavaScript library to: https://connectors.tableau.com/libs/tableauwdc-2.3.latest.js

That worked for both 2019.4 and at least one older version of Tableau Desktop (2019.1). I haven't tested it any more extensively.

**Comment by jasonlones** [comment]
I tested this change on 2019.4.1 and 2018.3.7 with great success!  Nice find, Andy!

Jason Lones
IT Analyst, Sr.
Duke Office of Clinical Research (DOCR)
School of Medicine
Phone: (919) 668-1787

Need REDCap help?  Check out remote office hours every Thursday at 2p ET: via WebEx<https://dukemed.webex.com/dukemed/j.php?MTID=m80cefa3357146919ec3fbb4e15cd9ac8>.

**Comment by 274188A** [comment]
I'd recommend adding a comment above that setting so folks know to check they have the latest version as the default can obviously become outdated. Thanks for the find Andy!

**Comment by lsgs** [comment]
Thanks very much @aarenson! I've also had success with updating the js to https://connectors.tableau.com/libs/tableauwdc-2.3.latest.js. And for me it also worked with 2018.1.

Note to all: as @aarenson states above you can update the Tableau js used in the module configuration dialog within REDCap's Control Center -> External Modules page.
